version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /.*
  script: quadroDeAnuncios.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest